// Copyright 2020-present Etherna SA
// This file is part of Scrinium.
//
// Scrinium is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// Scrinium is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with Scrinium.
// If not, see <https://www.gnu.org/licenses/>.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Etherna.Scrinium.Core.Generators
{
    /// <summary>
    /// Generates the proxy model types: for each
    /// concrete entity model of the compilation, a sealed subclass overriding its virtual
    /// members with the lazy loading and change candidate interception, implementing
    /// IReferenceable with generated per-member merges, and registered at assembly level
    /// with GeneratedProxyModelAttribute.
    /// </summary>
    [Generator]
    public class ProxyModelsGenerator : IIncrementalGenerator
    {
        // Consts.
        private const string EntityModelInterfaceFullName = "Etherna.Scrinium.Core.Domain.Models.IEntityModel";

        // Methods.
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var proxyModels = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { Modifiers: var modifiers } &&
                                                  !modifiers.Any(SyntaxKind.AbstractKeyword) &&
                                                  !modifiers.Any(SyntaxKind.StaticKeyword),
                    transform: static (syntaxContext, cancellationToken) =>
                        TryBuildProxyModelInfo(syntaxContext, cancellationToken))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!);

            // Emit one proxy class per entity model.
            context.RegisterSourceOutput(proxyModels, static (sourceContext, info) =>
                sourceContext.AddSource($"{info.ProxyName}.g.cs", EmitProxySource(info)));

            // Emit the assembly level proxy registrations.
            context.RegisterSourceOutput(proxyModels.Collect(), static (sourceContext, infos) =>
            {
                if (infos.Length == 0)
                    return;

                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated/>");
                foreach (var info in infos.OrderBy(i => i.ModelFullName))
                    builder.AppendLine(
                        $"[assembly: global::Etherna.Scrinium.Core.ProxyModels.GeneratedProxyModel(typeof({info.ModelFullName}), typeof({info.ProxyFullName}))]");

                sourceContext.AddSource("GeneratedProxyModelAttributes.g.cs", builder.ToString());
            });
        }

        // Helpers.
        private static ProxyModelInfo? TryBuildProxyModelInfo(
            GeneratorSyntaxContext syntaxContext,
            System.Threading.CancellationToken cancellationToken)
        {
            if (syntaxContext.SemanticModel.GetDeclaredSymbol(
                    (ClassDeclarationSyntax)syntaxContext.Node, cancellationToken) is not INamedTypeSymbol classSymbol)
                return null;

            /* Only concrete, non generic entity models are proxied: lazy loading and change
             * candidate marking only apply to them. Partial declarations process once. */
            if (classSymbol.IsAbstract ||
                classSymbol.IsStatic ||
                classSymbol.IsGenericType ||
                classSymbol.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal) ||
                classSymbol.ContainingType is not null ||
                !classSymbol.AllInterfaces.Any(i => i.ToDisplayString() == EntityModelInterfaceFullName))
                return null;
            //partial declarations process on the first declaration only
            if (!classSymbol.DeclaringSyntaxReferences[0].SyntaxTree.Equals(syntaxContext.Node.SyntaxTree) ||
                classSymbol.DeclaringSyntaxReferences[0].Span != syntaxContext.Node.Span)
                return null;

            return BuildProxyModelInfo(classSymbol, syntaxContext.SemanticModel.Compilation);
        }

        private static ProxyModelInfo BuildProxyModelInfo(INamedTypeSymbol classSymbol, Compilation compilation)
        {
            var methodAnalyzer = new AlteredMembersAnalyzer(classSymbol, compilation);
            var entityInterface = classSymbol.AllInterfaces
                .FirstOrDefault(i => i.IsGenericType && i.ConstructedFrom.ToDisplayString() == EntityModelInterfaceFullName + "<TKey>");
            var keyType = entityInterface?.TypeArguments[0];
            var info = new ProxyModelInfo
            {
                Accessibility = classSymbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal",
                IdPropertyName = FindEntityIdProperty(classSymbol, entityInterface)?.Name ?? "Id",
                KeyTypeIsNullable = keyType is { IsReferenceType: true } or
                                               { NullableAnnotation: NullableAnnotation.Annotated } or
                                               { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T },
                ModelFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                ModelName = classSymbol.Name,
                Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace ?
                    null :
                    classSymbol.ContainingNamespace.ToDisplayString(),
                ProxyName = classSymbol.Name + "Proxy"
            };
            info.ProxyFullName = info.Namespace is null ?
                $"global::{info.ProxyName}" :
                $"global::{info.Namespace}.{info.ProxyName}";

            // Collect overridable members and writable properties, most derived first.
            var visitedProperties = new HashSet<string>();
            var visitedMethods = new HashSet<string>();
            for (var type = classSymbol; type is not null && type.SpecialType != SpecialType.System_Object; type = type.BaseType)
            {
                foreach (var member in type.GetMembers())
                {
                    switch (member)
                    {
                        case IPropertySymbol { IsStatic: false, IsIndexer: false } property:
                            if (!visitedProperties.Add(property.Name))
                                continue;

                            /* The id member is not proxied: identity is definitionally present,
                             * never changes, and must stay readable also on an outdated
                             * instance, where it drives the model reload. Merges skip it too,
                             * because merged instances share the document by construction. */
                            if (property.Name == info.IdPropertyName)
                                continue;

                            //writable properties join the merges, with any accessibility
                            if (property.SetMethod is not null)
                                info.WritableProperties.Add(BuildWritablePropertyInfo(property, type, classSymbol));

                            //accessible virtual properties get interception overrides
                            if (IsOverridable(property))
                                info.OverriddenProperties.Add(BuildOverriddenPropertyInfo(property));
                            break;

                        case IMethodSymbol { IsStatic: false, MethodKind: MethodKind.Ordinary } method:
                            if (!visitedMethods.Add(GetMethodVisitKey(method)))
                                continue;
                            if (method.IsGenericMethod ||
                                GetOverrideRoot(method).ContainingType.SpecialType == SpecialType.System_Object ||
                                !IsOverridable(method))
                                continue;

                            info.OverriddenMethods.Add(BuildOverriddenMethodInfo(method, methodAnalyzer));
                            break;

                        default: break;
                    }
                }
            }

            //the id member is never an interception trigger
            foreach (var method in info.OverriddenMethods)
                method.AlteredMemberNames?.Remove(info.IdPropertyName);

            return info;
        }

        private static IPropertySymbol? FindEntityIdProperty(INamedTypeSymbol classSymbol, INamedTypeSymbol? entityInterface)
        {
            /* The identity property is the implicit implementation of the typed entity model
             * interface id. Models without it (or with an explicit implementation) fall back
             * to the "Id" name convention, like the lazy load emission does. */
            if (entityInterface?.GetMembers("Id").OfType<IPropertySymbol>().FirstOrDefault() is { } interfaceIdProperty &&
                classSymbol.FindImplementationForInterfaceMember(interfaceIdProperty) is IPropertySymbol implementingProperty &&
                implementingProperty.ExplicitInterfaceImplementations.IsEmpty)
                return implementingProperty;
            return null;
        }

        private static bool IsOverridable(ISymbol member) =>
            member is
            {
                DeclaredAccessibility: Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal,
                ContainingType.SpecialType: not SpecialType.System_Object
            } and ({ IsVirtual: true } or { IsOverride: true, IsSealed: false });

        private static IMethodSymbol GetOverrideRoot(IMethodSymbol method)
        {
            while (method.OverriddenMethod is not null)
                method = method.OverriddenMethod;
            return method;
        }

        private static string GetMethodVisitKey(IMethodSymbol method) =>
            method.Name + "(" + string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ")";

        private static OverriddenPropertyInfo BuildOverriddenPropertyInfo(IPropertySymbol property) =>
            new()
            {
                GetterAccessibility = property.GetMethod is { } getter ? GetAccessorModifier(getter, property) : null,
                GetterAccessibilityIsEmittable = property.GetMethod is { } emittableGetter && IsAccessorEmittable(emittableGetter),
                IsExtraElements = property.Name == "ExtraElements",
                Name = property.Name,
                PropertyAccessibility = GetAccessibilityModifier(property.DeclaredAccessibility),
                SetterAccessibility = property.SetMethod is { } setter ? GetAccessorModifier(setter, property) : null,
                SetterAccessibilityIsEmittable = property.SetMethod is { } emittableSetter && IsAccessorEmittable(emittableSetter),
                SetterIsInitOnly = property.SetMethod?.IsInitOnly ?? false,
                TypeFullName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            };

        private static bool IsAccessorEmittable(IMethodSymbol accessor) =>
            accessor.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal;

        private static string? GetAccessorModifier(IMethodSymbol accessor, IPropertySymbol property) =>
            accessor.DeclaredAccessibility == property.DeclaredAccessibility ?
                null :
                GetAccessibilityModifier(accessor.DeclaredAccessibility);

        private static string GetAccessibilityModifier(Accessibility accessibility) =>
            accessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                _ => "private"
            };

        private static OverriddenMethodInfo BuildOverriddenMethodInfo(IMethodSymbol method, AlteredMembersAnalyzer methodAnalyzer) =>
            new()
            {
                Accessibility = GetAccessibilityModifier(method.DeclaredAccessibility),
                AlteredMemberNames = methodAnalyzer.ComputeAlteredMemberNames(method),
                Name = method.Name,
                Parameters = [.. method.Parameters.Select(p => new MethodParameterInfo
                {
                    Modifier = p.RefKind switch
                    {
                        RefKind.Ref => "ref ",
                        RefKind.Out => "out ",
                        RefKind.In => "in ",
                        _ => p.IsParams ? "params " : ""
                    },
                    Name = p.Name,
                    TypeFullName = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) +
                                   (p.Type.IsReferenceType && p.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "")
                })],
                ReturnsVoid = method.ReturnsVoid,
                ReturnTypeFullName = method.ReturnsVoid ?
                    "void" :
                    method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) +
                    (method.ReturnType.IsReferenceType && method.ReturnType.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "")
            };

        private static WritablePropertyInfo BuildWritablePropertyInfo(
            IPropertySymbol property,
            INamedTypeSymbol declaringType,
            INamedTypeSymbol modelSymbol) =>
            new()
            {
                DeclaringTypeFullName = declaringType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                /* A member copies with a direct assignment when both accessors are reachable
                 * from the proxy subclass; any other member copies through reflection. */
                IsDirectlyAccessible =
                    property.GetMethod is { DeclaredAccessibility: Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal } &&
                    property.SetMethod is { DeclaredAccessibility: Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal, IsInitOnly: false },
                Name = property.Name
            };

        private static string EmitProxySource(ProxyModelInfo info)
        {
            var b = new StringBuilder();
            b.AppendLine("// <auto-generated/>");
            b.AppendLine("#nullable enable");
            b.AppendLine("#pragma warning disable");
            b.AppendLine();
            if (info.Namespace is not null)
            {
                b.AppendLine($"namespace {info.Namespace}");
                b.AppendLine("{");
            }

            b.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"Etherna.Scrinium.Core.Generators\", \"1.0\")]");
            b.AppendLine($"    {info.Accessibility} sealed class {info.ProxyName} :");
            b.AppendLine($"        {info.ModelFullName},");
            b.AppendLine($"        global::Etherna.Scrinium.Core.ProxyModels.IProxyModel,");
            b.AppendLine($"        global::Etherna.Scrinium.Core.ProxyModels.IReferenceable");
            b.AppendLine("    {");

            // Fields.
            b.AppendLine("        // Fields.");
            b.AppendLine("        private global::Etherna.Scrinium.Core.ProxyModels.IProxyModelsDbContext? proxyDbContext;");
            b.AppendLine("        private bool proxyIsSummary;");
            b.AppendLine("        private global::Etherna.Scrinium.Core.Options.ReactionMode proxyMissingOriginDocument =");
            b.AppendLine("            global::Etherna.Scrinium.Core.Options.ReactionMode.Throw;");
            b.AppendLine("        private global::System.Type? proxyOutdatedModelType;");
            b.AppendLine("        private readonly global::System.Collections.Generic.Dictionary<string, bool> proxySettedMemberNames = new(); //<memberName, isFromSummary>");
            b.AppendLine("        private global::Etherna.Scrinium.Core.Repositories.IRepository proxySourceRepository = null!; //bound right after creation");
            foreach (var property in info.OverriddenProperties.Where(p => p.GetterAccessibilityIsEmittable && !p.IsExtraElements).OrderBy(p => p.Name))
                b.AppendLine($"        private static readonly bool proxy{property.Name}ExposesMutation = global::Etherna.Scrinium.Core.ProxyModels.MutabilityAnalyzer.ExposesAutonomousMutation(typeof({property.TypeFullName}));");
            foreach (var property in info.WritableProperties.Where(p => !p.IsDirectlyAccessible).OrderBy(p => p.Name))
                b.AppendLine($"        private static readonly global::System.Reflection.PropertyInfo proxy{property.Name}Property = typeof({property.DeclaringTypeFullName}).GetProperty(\"{property.Name}\", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance)!;");
            b.AppendLine();

            // Properties.
            b.AppendLine("        // Properties.");
            foreach (var property in info.OverriddenProperties.OrderBy(p => p.Name))
            {
                b.AppendLine($"        {property.PropertyAccessibility} override {property.TypeFullName} {property.Name}");
                b.AppendLine("        {");
                if (property.GetterAccessibilityIsEmittable)
                {
                    b.AppendLine($"            {WithSpace(property.GetterAccessibility)}get");
                    b.AppendLine("            {");
                    if (property.IsExtraElements)
                    {
                        /* The extra elements bag is never loaded data: a summary excludes it from
                         * its loaded members and clears it at deserialization, and a full document
                         * clears it once its fix function ran, so a full load could bring nothing
                         * into it. Its get never loads on a summary, whoever reads it: the
                         * reference write clearing it, or the class map extra elements write. */
                        b.AppendLine("                //the extra elements bag is never loaded data: no summary load on its get");
                        b.AppendLine("                ThrowIfProxyOutdated();");
                    }
                    else
                    {
                        b.AppendLine($"                OnProxyMemberGet(\"{property.Name}\", proxy{property.Name}ExposesMutation);");
                    }
                    b.AppendLine($"                return base.{property.Name};");
                    b.AppendLine("            }");
                }
                if (property.SetterAccessibilityIsEmittable)
                {
                    var setterKeyword = property.SetterIsInitOnly ? "init" : "set";
                    b.AppendLine($"            {WithSpace(property.SetterAccessibility)}{setterKeyword}");
                    b.AppendLine("            {");
                    b.AppendLine($"                OnProxyMemberSet(\"{property.Name}\");");
                    b.AppendLine($"                base.{property.Name} = value;");
                    b.AppendLine("            }");
                }
                b.AppendLine("        }");
                b.AppendLine();
            }

            //IProxyModel and IReferenceable properties
            b.AppendLine("        global::System.Type? global::Etherna.Scrinium.Core.ProxyModels.IProxyModel.OutdatedModelType => proxyOutdatedModelType;");
            b.AppendLine("        bool global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.IsSummary => proxyIsSummary;");
            b.AppendLine("        global::Etherna.Scrinium.Core.Options.ReactionMode global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.MissingOriginDocument =>");
            b.AppendLine("            proxyMissingOriginDocument;");
            b.AppendLine("        global::System.Collections.Generic.IEnumerable<string> global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.SettedMemberNames =>");
            b.AppendLine("            global::System.Linq.Enumerable.ToArray(proxySettedMemberNames.Keys);");
            b.AppendLine("        global::Etherna.Scrinium.Core.Repositories.IRepository global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.SourceRepository => proxySourceRepository;");
            b.AppendLine();
            b.AppendLine("        // Private properties.");
            b.AppendLine("        //the proxy models surface of the db context owning the source repository");
            b.AppendLine("        private global::Etherna.Scrinium.Core.ProxyModels.IProxyModelsDbContext ProxySourceDbContext =>");
            b.AppendLine("            (global::Etherna.Scrinium.Core.ProxyModels.IProxyModelsDbContext)proxySourceRepository.DbContext;");
            b.AppendLine();

            // Methods.
            b.AppendLine("        // Methods.");
            foreach (var method in info.OverriddenMethods.OrderBy(m => m.Name))
            {
                var parameterDeclarations = string.Join(", ", method.Parameters.Select(p => $"{p.Modifier}{p.TypeFullName} {p.Name}"));
                var parameterForwards = string.Join(", ", method.Parameters.Select(p => $"{ForwardModifier(p.Modifier)}{p.Name}"));
                var alteredMembers = method.AlteredMemberNames is null ?
                    "null" :
                    method.AlteredMemberNames.Count == 0 ?
                        "global::System.Array.Empty<string>()" :
                        "new[] { " + string.Join(", ", method.AlteredMemberNames.Select(n => $"\"{n}\"")) + " }";

                b.AppendLine($"        {method.Accessibility} override {method.ReturnTypeFullName} {method.Name}({parameterDeclarations})");
                b.AppendLine("        {");
                b.AppendLine($"            OnProxyMethodInvoke({alteredMembers});");
                b.AppendLine($"            {(method.ReturnsVoid ? "" : "return ")}base.{method.Name}({parameterForwards});");
                b.AppendLine("        }");
                b.AppendLine();
            }

            //IProxyModel and IReferenceable methods
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IProxyModel.BindProxy(");
            b.AppendLine("            global::Etherna.Scrinium.Core.IDbContext? dbContext,");
            b.AppendLine("            global::Etherna.Scrinium.Core.Repositories.IRepository sourceRepository)");
            b.AppendLine("        {");
            b.AppendLine("            //the binding is fail-fast: a db context serving proxies implements their surface");
            b.AppendLine("            proxyDbContext = (global::Etherna.Scrinium.Core.ProxyModels.IProxyModelsDbContext?)dbContext;");
            b.AppendLine("            proxySourceRepository = sourceRepository;");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IProxyModel.SetOutdatedModelType(global::System.Type actualModelType) =>");
            b.AppendLine("            proxyOutdatedModelType = actualModelType;");
            b.AppendLine();
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.ClearSettedMembers() =>");
            b.AppendLine("            proxySettedMemberNames.Clear();");
            b.AppendLine();
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.MergeFullModel(object fullModel)");
            b.AppendLine("        {");
            b.AppendLine("            /* A full model of another type of the hierarchy can't merge: the caller");
            b.AppendLine("             * resolves the outdated instance, so the merge is skipped here. */");
            b.AppendLine($"            if (fullModel is {info.ModelFullName} typedFullModel)");
            b.AppendLine("                MergeProxyFullModel(typedFullModel);");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.MergeSummaryModel(object summaryModel)");
            b.AppendLine("        {");
            b.AppendLine("            if (summaryModel is not global::Etherna.Scrinium.Core.ProxyModels.IReferenceable summaryReferenceable ||");
            b.AppendLine($"                summaryModel is not {info.ModelFullName} typedSummaryModel)");
            b.AppendLine("                return;");
            b.AppendLine();
            b.AppendLine("            /* One document materializes one single instance, whatever the references reaching");
            b.AppendLine("             * it: an instance reached also by a stricter reference keeps its stricter");
            b.AppendLine("             * reaction to a missing origin document. */");
            b.AppendLine("            if (summaryReferenceable.MissingOriginDocument > proxyMissingOriginDocument)");
            b.AppendLine("                proxyMissingOriginDocument = summaryReferenceable.MissingOriginDocument;");
            b.AppendLine();
            b.AppendLine("            /* Merging two summaries is additive only: copy just the members that the current");
            b.AppendLine("             * model doesn't have at all. Suppress change tracking on the merge: the copied");
            b.AppendLine("             * members are loaded data, not changes to persist. */");
            b.AppendLine("            using (ProxySourceDbContext.SuppressChangeTracking())");
            b.AppendLine("            {");
            b.AppendLine("                var summaryModelMemberNames = global::System.Linq.Enumerable.ToHashSet(summaryReferenceable.SettedMemberNames);");
            foreach (var property in info.WritableProperties.OrderBy(p => p.Name))
            {
                b.AppendLine($"                if (summaryModelMemberNames.Contains(\"{property.Name}\") && !proxySettedMemberNames.ContainsKey(\"{property.Name}\"))");
                b.AppendLine("                {");
                b.AppendLine(property.IsDirectlyAccessible ?
                    $"                    base.{property.Name} = typedSummaryModel.{property.Name};" :
                    $"                    global::Etherna.Scrinium.Core.ReflectionHelper.SetValue(this, proxy{property.Name}Property, global::Etherna.Scrinium.Core.ReflectionHelper.GetValue(typedSummaryModel, proxy{property.Name}Property));");
                b.AppendLine($"                    proxySettedMemberNames[\"{property.Name}\"] = true; //from summary");
                b.AppendLine("                }");
            }
            b.AppendLine("            }");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        void global::Etherna.Scrinium.Core.ProxyModels.IReferenceable.SetAsSummary(");
            b.AppendLine("            global::System.Collections.Generic.IEnumerable<string> summaryLoadedMemberNames,");
            b.AppendLine("            global::Etherna.Scrinium.Core.Options.ReactionMode missingOriginDocument)");
            b.AppendLine("        {");
            b.AppendLine("            proxyIsSummary = true;");
            b.AppendLine("            proxyMissingOriginDocument = missingOriginDocument;");
            b.AppendLine("            foreach (var memberName in summaryLoadedMemberNames)");
            b.AppendLine("                proxySettedMemberNames[memberName] = true;");
            b.AppendLine("        }");
            b.AppendLine();

            // Helpers.
            b.AppendLine("        // Helpers.");
            b.AppendLine("        private void MarkProxyChangeCandidate() =>");
            b.AppendLine("            proxyDbContext?.MarkChangeCandidate(this);");
            b.AppendLine();
            b.AppendLine($"        private void MergeProxyFullModel({info.ModelFullName}? fullModel)");
            b.AppendLine("        {");
            b.AppendLine("            if (fullModel is not null)");
            b.AppendLine("            {");
            b.AppendLine("                /* Copy from the full model every member not already loaded, or loaded from a");
            b.AppendLine("                 * summary: a full document read is authoritative. Suppress change tracking on");
            b.AppendLine("                 * the merge: the copied members are loaded data, not changes to persist. */");
            b.AppendLine("                using (ProxySourceDbContext.SuppressChangeTracking())");
            b.AppendLine("                {");
            foreach (var property in info.WritableProperties.OrderBy(p => p.Name))
            {
                b.AppendLine($"                    if (!proxySettedMemberNames.TryGetValue(\"{property.Name}\", out var {ToCamelCase(property.Name)}FromSummary) || {ToCamelCase(property.Name)}FromSummary)");
                b.AppendLine("                    {");
                b.AppendLine(property.IsDirectlyAccessible ?
                    $"                        base.{property.Name} = fullModel.{property.Name};" :
                    $"                        global::Etherna.Scrinium.Core.ReflectionHelper.SetValue(this, proxy{property.Name}Property, global::Etherna.Scrinium.Core.ReflectionHelper.GetValue(fullModel, proxy{property.Name}Property));");
                b.AppendLine($"                        proxySettedMemberNames[\"{property.Name}\"] = false;");
                b.AppendLine("                    }");
            }
            b.AppendLine("                }");
            b.AppendLine("            }");
            b.AppendLine();
            b.AppendLine("            proxyIsSummary = false;");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        private void OnProxyMemberGet(string memberName, bool exposesMutation)");
            b.AppendLine("        {");
            b.AppendLine("            /* A get of a not loaded member on a summary model loads the full document; a get");
            b.AppendLine("             * handing out mutable state marks the model as a change candidate, because a");
            b.AppendLine("             * change could then escape interception. */");
            b.AppendLine("            ThrowIfProxyOutdated();");
            b.AppendLine("            if (proxyIsSummary && !proxySettedMemberNames.ContainsKey(memberName))");
            b.AppendLine("                ProxyFullLoad(memberName);");
            b.AppendLine("            if (exposesMutation)");
            b.AppendLine("                MarkProxyChangeCandidate();");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        private void OnProxyMemberSet(string memberName)");
            b.AppendLine("        {");
            b.AppendLine("            ThrowIfProxyOutdated();");
            b.AppendLine("            proxySettedMemberNames[memberName] = false;");
            b.AppendLine("            MarkProxyChangeCandidate();");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        private void OnProxyMethodInvoke(string[]? alteredMemberNames)");
            b.AppendLine("        {");
            b.AppendLine("            /* A method invocation marks the model as a change candidate; a method altering a");
            b.AppendLine("             * not loaded member on a summary model loads the full document, else reports its");
            b.AppendLine("             * altered members as setted. A method with unknown altered members (no analyzable");
            b.AppendLine("             * source) conservatively loads the full document on a summary model. */");
            b.AppendLine("            ThrowIfProxyOutdated();");
            b.AppendLine("            MarkProxyChangeCandidate();");
            b.AppendLine("            if (alteredMemberNames is null)");
            b.AppendLine("            {");
            b.AppendLine("                if (proxyIsSummary)");
            b.AppendLine("                    ProxyFullLoad(null);");
            b.AppendLine("                return;");
            b.AppendLine("            }");
            b.AppendLine("            foreach (var memberName in alteredMemberNames)");
            b.AppendLine("            {");
            b.AppendLine("                if (proxyIsSummary)");
            b.AppendLine("                {");
            b.AppendLine("                    if (!proxySettedMemberNames.ContainsKey(memberName))");
            b.AppendLine("                    {");
            b.AppendLine("                        ProxyFullLoad(memberName);");
            b.AppendLine("                        break;");
            b.AppendLine("                    }");
            b.AppendLine("                }");
            b.AppendLine("                else");
            b.AppendLine("                {");
            b.AppendLine("                    proxySettedMemberNames[memberName] = false;");
            b.AppendLine("                }");
            b.AppendLine("            }");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        private void ProxyFullLoad(string? triggeringMemberName)");
            b.AppendLine("        {");
            b.AppendLine("            if (!proxyIsSummary)");
            b.AppendLine("                return;");
            if (info.KeyTypeIsNullable)
            {
                b.AppendLine($"            if (base.{info.IdPropertyName} is null)");
                b.AppendLine("                throw new global::System.InvalidOperationException(\"model or id can't be null\");");
            }
            b.AppendLine("            // React to the implicit lazy load, honoring the db context options.");
            b.AppendLine($"            ProxySourceDbContext.OnImplicitLazyLoad(typeof({info.ModelFullName}), triggeringMemberName);");
            b.AppendLine();
            b.AppendLine("            // Merge the full document to the current model, with a sync over async load.");
            b.AppendLine($"            var task = proxySourceRepository.TryFindOneAsync(base.{info.IdPropertyName}!);");
            b.AppendLine("            task.Wait();");
            b.AppendLine("            ThrowIfProxyOutdated(); //the load deduplication flags this instance on a document type change");
            b.AppendLine($"            if (task.Result is {info.ModelFullName} typedResult)");
            b.AppendLine("                MergeProxyFullModel(typedResult);");
            b.AppendLine("            else if (task.Result is null)");
            b.AppendLine("            {");
            b.AppendLine("                /* The origin document doesn't exist anymore: react to the db inconsistency,");
            b.AppendLine("                 * honoring the mode of the reference that deserialized this summary. Tolerating");
            b.AppendLine("                 * it, there is nothing to load, and the model gives up the summary state. */");
            b.AppendLine("                ProxySourceDbContext.OnMissingOriginDocument(this);");
            b.AppendLine("                MergeProxyFullModel(null);");
            b.AppendLine("            }");
            b.AppendLine("            //else: document of another type of the hierarchy, this instance is outdated");
            b.AppendLine("        }");
            b.AppendLine();
            b.AppendLine("        private void ThrowIfProxyOutdated()");
            b.AppendLine("        {");
            b.AppendLine("            /* An outdated instance denies any application interaction, but stays readable by");
            b.AppendLine("             * the library internals, running under change tracking suppression (e.g. the");
            b.AppendLine("             * member diffs of a referencing model at save time). */");
            b.AppendLine("            if (proxyOutdatedModelType is null || proxyDbContext?.IsChangeTrackingSuppressed == true)");
            b.AppendLine("                return;");
            b.AppendLine("            throw new global::Etherna.Scrinium.Core.Exceptions.ScriniumOutdatedModelTypeException(");
            b.AppendLine($"                $\"Model {{base.{info.IdPropertyName}}} was loaded as type {info.ModelName}, but its document is now of type \" +");
            b.AppendLine("                $\"{proxyOutdatedModelType.Name}: reload the model from its repository to get the current type\");");
            b.AppendLine("        }");

            b.AppendLine("    }");
            if (info.Namespace is not null)
                b.AppendLine("}");

            return b.ToString();
        }

        private static string WithSpace(string? modifier) =>
            modifier is null ? "" : modifier + " ";

        private static string ForwardModifier(string modifier) =>
            modifier is "ref " or "out " or "in " ? modifier : "";

        private static string ToCamelCase(string name) =>
            char.ToLowerInvariant(name[0]) + name.Substring(1);

        // Internal classes.
        private sealed class ProxyModelInfo
        {
            public string Accessibility { get; set; } = "public";
            public string IdPropertyName { get; set; } = "Id";
            public bool KeyTypeIsNullable { get; set; }
            public string ModelFullName { get; set; } = "";
            public string ModelName { get; set; } = "";
            public string? Namespace { get; set; }
            public List<OverriddenMethodInfo> OverriddenMethods { get; } = [];
            public List<OverriddenPropertyInfo> OverriddenProperties { get; } = [];
            public string ProxyFullName { get; set; } = "";
            public string ProxyName { get; set; } = "";
            public List<WritablePropertyInfo> WritableProperties { get; } = [];
        }

        private sealed class OverriddenPropertyInfo
        {
            public string? GetterAccessibility { get; set; }
            public bool GetterAccessibilityIsEmittable { get; set; }
            public bool IsExtraElements { get; set; }
            public string Name { get; set; } = "";
            public string PropertyAccessibility { get; set; } = "public";
            public string? SetterAccessibility { get; set; }
            public bool SetterAccessibilityIsEmittable { get; set; }
            public bool SetterIsInitOnly { get; set; }
            public string TypeFullName { get; set; } = "";
        }

        private sealed class OverriddenMethodInfo
        {
            public string Accessibility { get; set; } = "public";
            public List<string>? AlteredMemberNames { get; set; }
            public string Name { get; set; } = "";
            public List<MethodParameterInfo> Parameters { get; set; } = [];
            public bool ReturnsVoid { get; set; }
            public string ReturnTypeFullName { get; set; } = "void";
        }

        private sealed class MethodParameterInfo
        {
            public string Modifier { get; set; } = "";
            public string Name { get; set; } = "";
            public string TypeFullName { get; set; } = "";
        }

        private sealed class WritablePropertyInfo
        {
            public string DeclaringTypeFullName { get; set; } = "";
            public bool IsDirectlyAccessible { get; set; }
            public string Name { get; set; } = "";
        }
    }
}
