name: Build test and package master branch. Deploy to NuGet

on:
  push:
    branches:
    - master

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --configuration Release
      
    - name: Generate nuget package
      run: dotnet pack --configuration Release -o nupkg

    - name: Push packages
      run: dotnet nuget push './nupkg/*.nupkg' --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
